[template]
cargo_generate_version = ">=0.0.1"

[placeholders]
description = { type = "string", prompt = "Description for the crate?" }
username = { type = "string", prompt = "Name for the user?" }
ask_for_options = { type = "bool", prompt = "Make a choice too?", default = true }
features = { prompt = "Include features?", choices = [
    "serde",
    "async",
], default = [
    "serde",
], type = "array" }

[conditional.'ask_for_options'.placeholders.multi_choice]
type = "array"
prompt = "Please select one or more..."
choices = ["A", "B", "C", "D"]
default = ["B", "C"]
